In [39]:
import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory



In [40]:
train1 = pd.read_csv(r"C:\Users\Saranga\Desktop\FYP\My DNN\training_set_my.csv",header=None)



In [41]:
train1.drop(labels=[0],axis=0,inplace=True)
train1

0  1          2          3          4          5          6          7   \
1    1  1  33.970576  26.907248  19.104973  13.038405  10.198039  11.704700   
2    1  1  36.359318  28.844410  19.723083  12.649111   9.055385  10.630146   
3    1  1  32.649655  25.942244  18.357560  12.041595   8.544004   9.486833   
4    1  1  34.928498  28.792360  19.697716  13.601471  10.295630  12.041595   
5    1  1  33.286634  26.076810  18.357560  12.649111   9.055385   9.219544   
..  .. ..        ...        ...        ...        ...        ...        ...   
746  4  1  40.311289  40.816663  38.587563  34.985711  30.886890  24.596748   
747  4  1  39.924930  40.853396  39.217343  35.735137  31.320920  24.738634   
748  4  1  41.012193  41.725292  40.311289  36.069378  31.144823  25.495098   
749  4  1  39.824616  41.231056  37.643060  35.468296  30.479501  24.041631   
750  4  1  40.496913  41.340053  39.115214  36.055513  30.805844  24.839485   

            8          9   ...         44         45         46         47  \
1    14.422205  18.601075  ...  12.041595  15.000000  20.591260  25.553865   
2    14.422205  18.867962  ...  11.401754  14.866069  20.615528  25.961510   
3    13.892444  18.027756  ...   8.544004  12.806248  18.384776  24.758837   
4    15.524175  19.646883  ...  10.770330  15.000000  19.798990  26.248810   
5    13.892444  17.888544  ...   9.219544  13.000000  17.464249  24.041631   
..         ...        ...  ...        ...        ...        ...        ...   
746  19.313208  12.369317  ...  23.194827  20.024984  16.124516  10.440307   
747  19.235384  12.041595  ...  25.079872  21.189620  16.492422  11.045361   
748  20.000000  13.038405  ...  22.671568  20.000000  15.264338   9.848858   
749  18.439089  11.401754  ...  25.000000  21.633308  17.000000  11.401754   
750  19.104973  12.806248  ...  23.345235  20.518285  15.811388  10.295630   

            48         49         50         51         52  53  
1    32.756679  38.275318  41.400483  44.687806  45.254834   1  
2    33.526109  39.217343  43.462628  45.617979  45.650849   1  
3    31.144823  36.235342  40.804412  44.102154  44.777226   1  
4    33.421550  37.202150  42.190046  45.177428  45.188494   1  
5    30.364453  35.114100  39.924930  43.382024  44.777226   1  
..         ...        ...        ...        ...        ...  ..  
746   6.403124   7.615773  12.806248  19.723083  26.832816   0  
747   5.099020   4.472136  10.295630  18.384776  25.298221   0  
748   5.000000   6.082763  12.206556  19.798990  26.172505   0  
749   7.071068   6.000000  11.661904  19.209373  26.172505   0  
750   5.000000   6.000000  12.083046  19.723083  26.627054   0  

[750 rows x 54 columns]

In [42]:
test1 = pd.read_csv(r"C:\Users\Saranga\Desktop\FYP\My DNN\testing_set_my.csv",header=None)

In [43]:
test1.drop(labels=[0],axis=0,inplace=True)
test1

0  1          2          3          4          5          6          7   \
1    1  1  34.014703  27.018512  18.110770  12.649111   7.810250  10.049876   
2    1  1  33.970576  26.907248  19.209373  12.529964   9.055385   9.433981   
3    1  1  34.481879  27.202941  19.313208  13.038405   9.433981   9.000000   
4    1  1  33.241540  27.856777  20.615528  14.422205  11.401754  11.180340   
5    1  1  35.014283  28.017851  19.000000  12.165525   7.810250  10.198039   
..  .. ..        ...        ...        ...        ...        ...        ...   
146  4  1  40.224371  42.438190  39.115214  36.359318  31.906112  25.059928   
147  4  1  40.706265  41.593269  39.357337  35.777088  31.780497  25.632011   
148  4  1  41.436699  41.436699  39.319206  36.345564  30.413813  24.515301   
149  4  1  39.849718  40.804412  38.600518  35.735137  29.732137  23.769729   
150  4  1  40.049969  42.047592  38.052595  35.128336  31.144823  24.186773   

            8          9   ...         44         45         46         47  \
1    15.297059  18.248288  ...   9.000000  13.341664  18.973666  25.298221   
2    14.142136  17.029386  ...   9.899495  13.892444  18.384776  25.079872   
3    14.560220  18.027756  ...   9.219544  12.529964  19.209373  25.000000   
4    14.142136  17.262677  ...  11.401754  13.892444  19.104973  24.839485   
5    14.000000  19.026298  ...   9.055385  12.165525  18.027756  24.041631   
..         ...        ...  ...        ...        ...        ...        ...   
146  19.697716  12.649111  ...  25.553865  21.931712  17.088007  11.180340   
147  18.973666  12.369317  ...  22.847319  19.924859  15.297059  10.000000   
148  18.681542  12.083046  ...  24.596748  21.095023  16.401219  12.041595   
149  17.888544  11.661904  ...  24.698178  21.400935  16.278821  11.401754   
150  18.439089  11.704700  ...  24.698178  21.931712  16.643317  12.041595   

            48         49         50         51         52  53  
1    32.015621  37.107951  41.773197  44.407207  45.099889   1  
2    30.870698  36.235342  40.816663  43.829214  44.204072   1  
3    31.622777  37.443290  41.677332  44.294469  44.777226   1  
4    30.610456  35.000000  39.962482  43.416587  45.188494   1  
5    32.015621  36.878178  41.436699  44.181444  45.044423   1  
..         ...        ...        ...        ...        ...  ..  
146   6.082763   5.099020  11.401754  20.248457  26.419690   0  
147   5.385165   5.830952  12.206556  19.235384  26.400758   0  
148   7.280110   7.071068  12.041595  20.099751  27.294688   0  
149   6.082763   6.708204  12.041595  19.646883  27.513633   0  
150   7.280110   7.071068  12.165525  20.024984  26.076810   0  

[150 rows x 54 columns]

In [25]:
train = shuffle(train1)
test = shuffle(test1)
train

0      1          2          3          4          5          6   \
65  0.125  3.075  34.176015  29.546573  23.706539  18.867962  14.142136   
35  2.775  0.125  18.110770  17.464249  17.888544  21.260292  24.083189   
36  2.775  0.125  18.384776  17.464249  18.027756  21.023796  23.769729   
42  2.775  3.075  31.016125  28.284271  24.331050  21.587033  16.492422   
75  0.125  3.075  38.118237  34.132096  28.284271  23.345235  18.027756   
..    ...    ...        ...        ...        ...        ...        ...   
90    1.3    1.7  40.049969  36.000000  31.000000  25.079872  19.104973   
1   0.125  0.125  27.294688  22.561028  15.811388  10.630146   8.246211   
30  2.775  0.125  17.492856  16.278821  17.117243  19.924859  22.847319   
4   0.125  0.125  31.320920  24.515301  16.124516  10.440307   7.211103   
24  2.775  0.125  14.422205  13.038405  15.297059  18.000000  20.223748   

           7          8          9   ...         44         45         46  \
65   9.486833   9.219544  10.630146  ...   9.899495  12.369317  17.029386   
35  27.018512  29.410882  29.410882  ...  25.553865  30.016662  32.649655   
36  26.248810  28.792360  30.083218  ...  26.400758  30.413813  33.120990   
42  14.317821  12.041595  11.045361  ...  13.928388  13.341664  13.000000   
75  13.601471  10.816654  11.045361  ...  13.038405  13.601471  16.763055   
..        ...        ...        ...  ...        ...        ...        ...   
90  11.401754   5.830952   2.236068  ...   9.848858   5.099020   1.000000   
1    9.848858  13.453624  17.029386  ...   3.605551  10.000000  15.132746   
30  24.186773  26.419690  26.925824  ...  24.207437  28.319605  31.827661   
4    9.219544  13.601471  16.970563  ...   3.605551  10.295630  16.763055   
24  23.537205  25.000000  25.961510  ...  22.561028  25.961510  29.410882   

           47         48         49         50         51         52   53  
65  21.587033  25.961510  31.622777  35.468296  37.696154  39.560081  3.0  
35  35.777088  37.589892  38.078866  37.215588  35.510562  31.906112  1.0  
36  35.846897  38.013156  38.470768  37.576588  35.341194  30.870698  1.0  
42  14.142136  18.439089  20.880613  24.738634  28.861739  31.400637  2.0  
75  21.095023  26.019224  31.256999  35.355339  39.623226  41.436699  3.0  
..        ...        ...        ...        ...        ...        ...  ...  
90   7.071068  15.132746  22.203603  28.160256  34.058773  39.115214  4.0  
1   21.587033  28.635642  31.780497  35.902646  37.854986  39.623226  0.0  
30  33.241540  35.383612  36.124784  35.468296  32.649655  29.206164  1.0  
4   23.769729  29.614186  35.693137  39.812058  41.231056  41.231056  0.0  
24  31.622777  33.526109  34.481879  33.955854  30.805844  26.925824  1.0  

[100 rows x 54 columns]

In [28]:
X_train = train.iloc[:,2:53].values
X_train 


array([[34.17601498, 29.54657341, 23.70653918, ..., 35.4682957 ,
        37.69615365, 39.56008089],
       [18.11077028, 17.4642492 , 17.88854382, ..., 37.21558813,
        35.51056181, 31.90611227],
       [18.38477631, 17.4642492 , 18.02775638, ..., 37.57658846,
        35.34119409, 30.87069808],
       ...,
       [17.49285568, 16.2788206 , 17.11724277, ..., 35.4682957 ,
        32.64965543, 29.20616373],
       [31.32091953, 24.51530134, 16.1245155 , ..., 39.81205847,
        41.23105626, 41.23105626],
       [14.4222051 , 13.03840481, 15.29705854, ..., 33.95585369,
        30.8058436 , 26.92582404]])

In [29]:
X_test = test.iloc[:,2:53].values
X_test 

array([[34.13209633, 30.01666204, 26.        , ..., 28.63564213,
        32.89376841, 34.4818793 ],
       [43.41658669, 40.80441153, 34.66987165, ..., 29.        ,
        36.12478374, 40.45985665],
       [31.        , 28.0713377 , 23.19482701, ..., 26.2488095 ,
        29.12043956, 32.55764119],
       ...,
       [38.27531842, 35.84689666, 30.46309242, ..., 26.57066051,
        32.89376841, 36.76955262],
       [36.        , 32.01562119, 27.07397274, ..., 31.01612484,
        35.        , 39.01281841],
       [39.69886648, 38.41874542, 32.20248438, ..., 26.90724809,
        32.55764119, 38.18376618]])

In [30]:
Y_train_label = train.iloc[:,53].values.astype(int)
Y_train_label

array([3, 1, 1, 2, 3, 3, 1, 2, 0, 2, 4, 4, 4, 1, 4, 2, 0, 3, 3, 1, 2, 1,
       4, 0, 0, 4, 0, 3, 0, 4, 0, 0, 4, 3, 3, 3, 4, 4, 0, 3, 3, 2, 1, 3,
       0, 4, 2, 1, 1, 2, 3, 0, 0, 1, 2, 4, 0, 4, 1, 3, 3, 3, 3, 2, 3, 1,
       2, 1, 2, 4, 4, 0, 1, 1, 4, 2, 2, 4, 2, 0, 1, 1, 0, 2, 3, 1, 2, 0,
       4, 2, 3, 4, 2, 2, 0, 4, 0, 1, 0, 1])

In [31]:
Y_test_label = test.iloc[:,53].values.astype(int)
#Y_test_label = Y_test_label.astype(np.int)
Y_test_label

array([2, 4, 2, 2, 0, 1, 2, 1, 1, 1, 2, 2, 0, 4, 3, 4, 4, 3, 3, 4, 4, 3,
       0, 3, 1, 0, 1, 4, 3, 1, 3, 0, 1, 2, 2, 2, 1, 3, 0, 0, 0, 0, 2, 4,
       3, 0, 1, 4, 3, 4])

In [32]:
X_train_scaled = (X_train - X_train.min()) / (X_train.max() - X_train.min())
X_test_scaled = (X_test - X_test.min()) / (X_test.max() - X_test.min())
X_train_scaled

array([[0.6630185 , 0.57320681, 0.4599095 , ..., 0.68808889, 0.73130958,
        0.76746997],
       [0.35135096, 0.33880838, 0.34703974, ..., 0.72198655, 0.68890885,
        0.61898213],
       [0.35666671, 0.33880838, 0.34974048, ..., 0.72899   , 0.6856231 ,
        0.59889498],
       ...,
       [0.33936335, 0.31581093, 0.33207642, ..., 0.68808889, 0.63340695,
        0.56660283],
       [0.60762933, 0.47559958, 0.3128174 , ..., 0.77235837, 0.79988708,
        0.79988708],
       [0.27979238, 0.25294651, 0.29676464, ..., 0.65874734, 0.5976368 ,
        0.52236398]])

In [33]:
params_grid = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]

In [34]:
svm_model = GridSearchCV(SVC(), params_grid, cv=5)
svm_model.fit(X_train_scaled, Y_train_label)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 1000], 'kernel': ['linear']}])

In [35]:
print('Best score for training data:', svm_model.best_score_,"\n") 

Best score for training data: 1.0 



In [36]:
print('Best C:',svm_model.best_estimator_.C,"\n") 
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")



Best C: 100 

Best Kernel: rbf 

Best Gamma: 0.001 



In [37]:
final_model = svm_model.best_estimator_
Y_pred_label = final_model.predict(X_test_scaled)
Y_pred_label

array([2, 4, 2, 2, 0, 1, 2, 1, 1, 1, 2, 2, 0, 4, 3, 4, 4, 3, 3, 4, 4, 3,
       0, 3, 1, 0, 1, 4, 3, 1, 3, 0, 1, 2, 2, 2, 1, 3, 0, 0, 0, 0, 2, 4,
       3, 0, 1, 4, 3, 4])

In [38]:
Y_test_label

array([2, 4, 2, 2, 0, 1, 2, 1, 1, 1, 2, 2, 0, 4, 3, 4, 4, 3, 3, 4, 4, 3,
       0, 3, 1, 0, 1, 4, 3, 1, 3, 0, 1, 2, 2, 2, 1, 3, 0, 0, 0, 0, 2, 4,
       3, 0, 1, 4, 3, 4])

In [18]:
print(classification_report(Y_test_label,Y_pred_label))



              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00        10
           4       1.00      1.00      1.00        10
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00        10
           7       1.00      1.00      1.00        10
           8       1.00      1.00      1.00        10
           9       1.00      1.00      1.00        10
          10       1.00      1.00      1.00        10
          11       1.00      1.00      1.00        10
          12       1.00      1.00      1.00        10
          13       1.00      1.00      1.00        10
          14       1.00      1.00      1.00        10

    accuracy                           1.00       150
   macro avg       1.00      1.00      1.00       150
weighted avg       1.00   

In [19]:
print("Training set score for SVM: %f" % final_model.score(X_train_scaled , Y_train_label))
print("Testing  set score for SVM: %f" % final_model.score(X_test_scaled  , Y_test_label ))

svm_model.score

Training set score for SVM: 1.000000
Testing  set score for SVM: 1.000000


<bound method BaseSearchCV.score of GridSearchCV(cv=5, estimator=SVC(),
             param_grid=[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [1, 10, 100, 1000], 'kernel': ['linear']}])>

In [20]:
print(confusion_matrix(Y_test_label,Y_pred_label))

[[10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 10  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 10  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 10]]
